/** Curated emoji set for reactions and the composer, grouped Slack-style. Each item is [emoji, search keywords]. */
export type EmojiCategory = { name: string; items: [string, string][] };

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys",
    items: [
    ["😀", "grin"],
    ["😃", "smile"],
    ["😄", "happy"],
    ["😁", "beam"],
    ["😆", "laugh"],
    ["😅", "sweat"],
    ["🤣", "rofl"],
    ["😂", "joy tears"],
    ["🙂", "slight smile"],
    ["😉", "wink"],
    ["😊", "blush"],
    ["😇", "angel"],
    ["🥰", "love"],
    ["😍", "heart eyes"],
    ["🤩", "star struck"],
    ["😘", "kiss"],
    ["😋", "yum"],
    ["😛", "tongue"],
    ["😜", "crazy"],
    ["🤪", "zany"],
    ["🤗", "hug"],
    ["🤭", "oops"],
    ["🤫", "shush"],
    ["🤔", "thinking"],
    ["🤐", "zip"],
    ["😐", "neutral"],
    ["😑", "expressionless"],
    ["😶", "speechless"],
    ["😏", "smirk"],
    ["😒", "unamused"],
    ["🙄", "eye roll"],
    ["😬", "grimace"],
    ["😌", "relieved"],
    ["😔", "pensive"],
    ["😪", "sleepy"],
    ["😴", "sleep"],
    ["😷", "mask"],
    ["🤒", "sick"],
    ["🥵", "hot"],
    ["🥶", "cold"],
    ["🥳", "party"],
    ["😎", "cool"],
    ["🤓", "nerd"],
    ["🧐", "monocle"],
    ["😕", "confused"],
    ["😟", "worried"],
    ["🙁", "frown"],
    ["😮", "wow"],
    ["😲", "astonished"],
    ["😳", "flushed"],
    ["🥺", "pleading"],
    ["😢", "cry"],
    ["😭", "sob"],
    ["😱", "scream"],
    ["😤", "triumph"],
    ["😡", "angry"],
    ["🤯", "mind blown"],
    ["🫡", "salute"],
    ["🫠", "melting"],
    ],
  },
  {
    name: "Gestures",
    items: [
    ["👍", "thumbs up yes"],
    ["👎", "thumbs down no"],
    ["👏", "clap"],
    ["🙌", "raised hands"],
    ["👐", "open hands"],
    ["🤝", "handshake deal"],
    ["🙏", "thanks pray"],
    ["✌️", "peace"],
    ["🤞", "fingers crossed"],
    ["🤟", "love you"],
    ["🤘", "rock"],
    ["👌", "ok"],
    ["🤌", "pinched"],
    ["👈", "left"],
    ["👉", "right"],
    ["👆", "up"],
    ["👇", "down"],
    ["☝️", "point"],
    ["✋", "hand"],
    ["🖐️", "five"],
    ["👋", "wave hi bye"],
    ["💪", "strong"],
    ["🫶", "heart hands"],
    ["✍️", "writing"],
    ["🧠", "brain"],
    ["👀", "eyes look"],
    ["👁️", "eye"],
    ],
  },
  {
    name: "Hearts",
    items: [
    ["❤️", "heart love"],
    ["🧡", "orange heart"],
    ["💛", "yellow heart"],
    ["💚", "green heart"],
    ["💙", "blue heart"],
    ["💜", "purple heart"],
    ["🖤", "black heart"],
    ["🤍", "white heart"],
    ["💔", "broken heart"],
    ["❣️", "heart exclamation"],
    ["💕", "two hearts"],
    ["💞", "revolving hearts"],
    ["💓", "beating heart"],
    ["💗", "growing heart"],
    ["💖", "sparkling heart"],
    ["💯", "hundred"],
    ["💥", "boom"],
    ["💫", "dizzy"],
    ["✨", "sparkles"],
    ["⭐", "star"],
    ["🌟", "glowing star"],
    ],
  },
  {
    name: "Celebrate",
    items: [
    ["🎉", "party tada"],
    ["🎊", "confetti"],
    ["🥂", "cheers"],
    ["🍾", "champagne"],
    ["🎈", "balloon"],
    ["🎁", "gift"],
    ["🏆", "trophy win"],
    ["🥇", "gold first"],
    ["🥈", "silver"],
    ["🥉", "bronze"],
    ["🏅", "medal"],
    ["🎯", "target goal"],
    ["🚀", "rocket launch"],
    ["🔥", "fire lit"],
    ["⚡", "lightning"],
    ["🌈", "rainbow"],
    ["👑", "crown"],
    ["💎", "gem"],
    ],
  },
  {
    name: "Work",
    items: [
    ["💼", "briefcase job"],
    ["📈", "growth chart"],
    ["📉", "decline"],
    ["📊", "bar chart"],
    ["🗂️", "folders"],
    ["📁", "folder"],
    ["📝", "memo note"],
    ["📌", "pin"],
    ["📎", "paperclip"],
    ["🔗", "link"],
    ["📅", "calendar"],
    ["⏰", "alarm"],
    ["⏳", "hourglass"],
    ["✅", "done check"],
    ["☑️", "checkbox"],
    ["❌", "cross no"],
    ["⚠️", "warning"],
    ["❓", "question"],
    ["❗", "exclamation"],
    ["💡", "idea bulb"],
    ["🔍", "search"],
    ["🛠️", "tools"],
    ["⚙️", "settings"],
    ["💻", "laptop"],
    ["🖥️", "desktop"],
    ["📱", "phone"],
    ["🎓", "graduate"],
    ["📚", "books learn"],
    ["🧑‍💻", "developer"],
    ["👩‍🏫", "teacher"],
    ["🧑‍🎓", "student"],
    ["🤖", "robot ai"],
    ["📣", "announce"],
    ["🎤", "mic"],
    ["🎥", "video camera"],
    ["📷", "camera"],
    ],
  },
  {
    name: "Nature",
    items: [
    ["🌱", "seedling grow"],
    ["🌿", "herb"],
    ["🍀", "clover luck"],
    ["🌻", "sunflower"],
    ["🌸", "blossom"],
    ["🌍", "earth africa"],
    ["☀️", "sun"],
    ["🌙", "moon"],
    ["☁️", "cloud"],
    ["🌧️", "rain"],
    ["❄️", "snow"],
    ["🌊", "wave"],
    ["🦁", "lion"],
    ["🐘", "elephant"],
    ["🦒", "giraffe"],
    ["🐶", "dog"],
    ["🐱", "cat"],
    ["🦋", "butterfly"],
    ["🐝", "bee"],
    ],
  },
  {
    name: "Food",
    items: [
    ["☕", "coffee"],
    ["🍵", "tea"],
    ["🍕", "pizza"],
    ["🍔", "burger"],
    ["🍟", "fries"],
    ["🌮", "taco"],
    ["🍣", "sushi"],
    ["🍩", "donut"],
    ["🍪", "cookie"],
    ["🎂", "cake birthday"],
    ["🍰", "shortcake"],
    ["🍎", "apple"],
    ["🍌", "banana"],
    ["🥑", "avocado"],
    ["🍿", "popcorn"],
    ],
  },
];
